package pl.dans.plugins.hunters;


public enum Achievement {
    FIRST_DAMAGE,
    FIRST_BLOOD,
    FIRST_ENCHANTMENT_TABLE,
    FIRST_BREWING_STAND,
    FIRST_BOW,
    FIRST_FISHING_ROD,
    FIRST_EMERALD_BLOCK,
    FIRST_REDSTONE_BLOCK,
    FIRST_NETHER_PORTAL,
    FIRST_SADDLE,
    FIRST_ENDERPEARL,
    FIRST_CACTUS_IN_A_FLOWER_POT,
    FIRST_KILLED_WITCH,
    FIRST_ANVIL,
    FIRST_MINECART,
    FIRST_RECORD_IN_JUKEBOX,
    FIRST_CRAFTING_TABLE,
    FIRST_CHEST,
    FALL_DAMAGE,
    FIRST_GOLDEN_APPLE,
    FIRST_DIAMOND_SHOVEL,
    SPEED_POTION,
    STRENGTH_POTION,
    GOLDEN_APPLES,
    CHEST,
    LONGSHOT_100,
    LONGSHOT_60,
    IRONMEN
}
