name: AchievementHunters
main: pl.dans.plugins.hunters.AchievementHunters
version: 1.0
  
commands:
  ahunters:
    description: Basic commands for AchievementHunters
    usage: /<command> <subcommand>
    permission: AchievementHunters.basic
    permission-message: You don't have <permission>
  alist:
    description: Basic commands for AchievementHunters
    usage: /<command>
permissions:
    AchievementHunters.basic:
        description: Allows use of the commands in the plugin
        default: op
